# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dyna_pca',
                'doc_host': 'https://chiaraf10.github.io',
                'git_url': 'https://github.com/chiaraf10/dyna_pca',
                'lib_path': 'dyna_pca'},
  'syms': { 'dyna_pca.core': {'dyna_pca.core.foo': ('core.html#foo', 'dyna_pca/core.py')},
            'dyna_pca.core_functions': {},
            'dyna_pca.get_matrix': {},
            'dyna_pca.get_pca': {},
            'dyna_pca.mseloss': {},
            'dyna_pca.norm': {},
            'dyna_pca.pca': {},
            'dyna_pca.time_history': {},
            'dyna_pca.train_split': {}}}
