# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dyna_PCA',
                'doc_host': 'https://chiaraf10.github.io',
                'git_url': 'https://github.com/chiaraf10/dyna_PCA',
                'lib_path': 'dyna_PCA'},
  'syms': {'dyna_PCA.core': {'dyna_PCA.core.foo': ('core.html#foo', 'dyna_PCA/core.py')}}}
